### ISSUE TITLE
Request: Case battery info for WF-1000XM3

### ISSUE THREAD

**Issue by raddacle** [ClusterM/sony-headphones-control#3]
First off, I'm so happy to have found this and really appreciate your work towards this app! I'd be happy to donate to your coffee fund if that's an option.

Now that WF-1000XM3 can get the battery level for the case, I'm wondering whether you would be able to get that value as a variable for tasker? I imagine this could be setup similar to other plugins, where there is query action that pulls the plugin's variables.

**Comment by ClusterM** [comment]
Sorry, I'm using WI-1000X, it has not case, so I can't test this feature.

**Comment by raddacle** [comment]
Do you know of a direction I can look into to try and add this to the code?
