### ISSUE TITLE
Sony WH-1000XM4 support

### ISSUE THREAD

**Issue by Unknown27** [ClusterM/sony-headphones-control#9]
As the title suggests, are the Sony WH-1000XM4 going to be supported? I tested the app and works fine but the tasker plugin cannot turn on ANC again after disabling it...
All other options work fine when using them from tasker task plugin.

**Comment by ClusterM** [comment]
I have not such headphones to test. You can fork project and try it yourself.

**Comment by Unknown27** [comment]
As the app works fine, I suppose it's a tasker issue...
So, no blame on you at all.

Thank you.
